### ISSUE TITLE
cleanup of Examples folders?

### ISSUE THREAD

**Issue by robertgiessmann** [EnzymeML/PyEnzyme#4]
I get a big confused here. I found three folders containing omex files:

* https://github.com/EnzymeML/PyEnzyme/tree/main/templates
* https://github.com/EnzymeML/PyEnzyme/tree/main/pyenzyme/Examples
* https://github.com/EnzymeML/PyEnzyme/tree/main/pyenzyme/Resources/Examples

Are they all equally valid files? Is there an opportunity to cleanup here? Thanks in advance! :)

**Comment by JR-1991** [comment]
Thanks for the comment! 

Those files are valid, since they were generated with the PyEnzyme version present in the repo. Of course, when we are finished with the development of the next version, those will be updated and everything cleaned up. 

I might add, that it is planned to move the examples out of the /pyenzyme dir to increase visibility.
