### ISSUE TITLE
Correct structure in the REST API measurement-documentation

### ISSUE THREAD

**Issue by StephanM87** [EnzymeML/PyEnzyme#41]
I found this in the description of the REST-API documentation: https://enzymeml.sloppy.zone/redoc#operation/create_EnzymeML_create_post

Is it correct that there are two unnamed dicts concentrated in a row in the measurements--> species dict?

![grafik](https://user-images.githubusercontent.com/48381090/161743559-abe787b3-e39a-41ec-8555-bfbea28dee7d.png)

**Comment by JR-1991** [comment]
Thanks for submitting! As denoted in the `species_dict` description, it is in fact a dictionary that holds at most two keys, which are `proteins` and/or `reactants`. Each of these then hold `MeasurementData` that corresponds to replicates and initial concentration. Splitting both `reactants` and `proteins` is done to support different high-level features that operate on measurements, but are planned to be substituted with a better solution.

In addition, since the REST-API documentation is based of the PyDantic model, this directly translates to the documentation and might seem confusing at first. We might have to think about a better documentation on this matter. What would you think would suit your needs best?

**Comment by StephanM87** [comment]
Hey Thanks for answering! Ah now I get it! 🥳 ok that's pretty clever! What confused me was the two **property name** elements. But now it makes sense! 
In my opinion, it would be very nice to see a example json :) I think an example in combination with your documentation would be a good combination.

**Comment by JR-1991** [comment]
Thats a great idea! Where would you want to access the example? I think the general documentation would be a good primer.

**Comment by StephanM87** [comment]
absolutely! I would search it on the readme page on the entry for the REST-API: In my opinion, it would be nice to have a link to a json available there
![grafik](https://user-images.githubusercontent.com/48381090/161972855-15f6e07e-129d-4cd8-9f81-636efe306564.png)

**Comment by JR-1991** [comment]
Has been fixed by adding the example directly to the REST-API documentation. In addition, the `unit`-part is now also removed, since it is not used. as a consequence the `unit_dict` is now private so that FastAPI won't include it in the OpenAPI  schema. This is linked to issue #26
